# Generated by Django 3.1.3 on 2020-12-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
