# Generated by Django 3.1.3 on 2020-12-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
