# Generated by Django 3.1.3 on 2020-12-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='HelpContact',
        ),
    ]
