# Generated by Django 3.1.3 on 2020-12-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clinet_Date_Of_Birth',
            new_name='client_Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clinet_Email',
            new_name='client_Email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clinet_Mobile',
            new_name='client_Mobile',
        ),
    ]
