# Generated by Django 3.1.3 on 2020-12-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20201215_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
