# Generated by Django 3.1.3 on 2020-12-15 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
    ]
