# Generated by Django 3.1.3 on 2020-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_remove_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_Referance',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
    ]
