# Generated by Django 3.1.3 on 2020-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_auto_20201215_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_1',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_2',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_3',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_4',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_5',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Diagnosis_6',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
    ]
