# Generated by Django 3.1.3 on 2020-12-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_auto_20201215_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address_1', models.CharField(max_length=500)),
                ('address_2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('zip', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
            ],
        ),
    ]
