# Generated by Django 3.1.3 on 2020-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_medicalshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalshop',
            name='logo',
            field=models.ImageField(default='', upload_to='medical'),
            preserve_default=False,
        ),
    ]
