# Generated by Django 3.1.3 on 2020-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_medicalshop_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_1',
            new_name='client_Disease_1',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_2',
            new_name='client_Disease_2',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_3',
            new_name='client_Disease_3',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_4',
            new_name='client_Disease_4',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_5',
            new_name='client_Disease_5',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Diagnosis_6',
            new_name='client_Disease_6',
        ),
    ]
