# Generated by Django 3.1.3 on 2020-12-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_auto_20201216_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_Disease_1',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Disease_2',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Disease_3',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Disease_4',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Disease_5',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_Disease_6',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
