# Generated by Django 3.1.3 on 2020-12-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0019_auto_20201216_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalshop',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='state',
        ),
        migrations.RemoveField(
            model_name='medicalshop',
            name='zip',
        ),
    ]
