# Generated by Django 3.1.3 on 2020-12-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0020_auto_20201216_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalShop',
            new_name='Medical_Shop',
        ),
    ]
