# Generated by Django 3.1.3 on 2020-12-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_auto_20201216_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medical_Shop',
            new_name='MedicalShop',
        ),
    ]
