# Generated by Django 3.1.3 on 2020-12-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0022_auto_20201216_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalshop',
            name='address_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='address_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='logo',
            field=models.ImageField(default='', upload_to='medical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='mobile',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='zip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
