# Generated by Django 3.1.3 on 2020-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0025_auto_20201216_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=5),
        ),
    ]
