# Generated by Django 3.1.3 on 2020-12-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0026_auto_20201216_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment',
            field=models.CharField(max_length=10),
        ),
    ]
