# Generated by Django 3.1.3 on 2020-12-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0027_auto_20201216_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
