# Generated by Django 3.1.3 on 2020-12-16 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0028_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('payment', models.CharField(max_length=10)),
                ('bill_date', models.DateField()),
                ('timestamp', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
