# Generated by Django 3.1.3 on 2020-12-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0029_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
