# Generated by Django 3.1.3 on 2020-12-16 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0031_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
