# Generated by Django 3.1.3 on 2020-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0032_auto_20201216_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(default=456),
            preserve_default=False,
        ),
    ]
